--- #YAML:1.0
name:               WWW-Hanako
version:            0.05
abstract:           Perl interface for Hanako(Pollen observation system at Japan)
author:
    - Tsukasa Hamano <hamano@klab.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:  0
    Test::More:      0
    Web::Scraper:    0
    WWW::Mechanize:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
